version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  server:
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
      - CORS_ORIGIN=http://${VPS_IP}:3000
      - JWT_SECRET=${JWT_SECRET}
      - SALT_ROUND=${SALT_ROUND}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_MAIL=${SMTP_MAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - PAYPAL_API_URL=${PAYPAL_API_URL}
    depends_on:
      - db
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=http://${VPS_IP}:${PORT}
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  db_data:
